// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_WD2DUKhPlxrcLN-kj2CaRQasSqYkjf0',
    appId: '1:934099003137:web:003c3275c9f9c47eb39d00',
    messagingSenderId: '934099003137',
    projectId: 'beresin-8d631',
    authDomain: 'beresin-8d631.firebaseapp.com',
    storageBucket: 'beresin-8d631.firebasestorage.app',
    measurementId: 'G-Y3YJK2SW3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEyIHGka-zA_MFhm6rmjXZMYfzMB0c2OY',
    appId: '1:934099003137:android:22fbbdd9f87d4354b39d00',
    messagingSenderId: '934099003137',
    projectId: 'beresin-8d631',
    storageBucket: 'beresin-8d631.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnhgh4T5H2cpDCRFdh9CEpqJjoEchWtkM',
    appId: '1:934099003137:ios:57aceedac8ca5a2ab39d00',
    messagingSenderId: '934099003137',
    projectId: 'beresin-8d631',
    storageBucket: 'beresin-8d631.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnhgh4T5H2cpDCRFdh9CEpqJjoEchWtkM',
    appId: '1:934099003137:ios:57aceedac8ca5a2ab39d00',
    messagingSenderId: '934099003137',
    projectId: 'beresin-8d631',
    storageBucket: 'beresin-8d631.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_WD2DUKhPlxrcLN-kj2CaRQasSqYkjf0',
    appId: '1:934099003137:web:bdb43abe02ecf726b39d00',
    messagingSenderId: '934099003137',
    projectId: 'beresin-8d631',
    authDomain: 'beresin-8d631.firebaseapp.com',
    storageBucket: 'beresin-8d631.firebasestorage.app',
    measurementId: 'G-MKRXHCP8GS',
  );
}
